[package]
name = "ruspiro-mailbox"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.3.0" # remember to update html_root_url
description = "Raspberry Pi mailbox property tag interface API."
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-mailbox"
documentation = "https://docs.rs/ruspiro-mailbox/0.3.0"
readme = "README.md"
keywords = ["RusPiRo", "mailbox", "propertytag", "raspberrypi", "baremetal"]
categories = ["no-std", "embedded"]
edition = "2018"

[badges]
travis-ci = { repository = "RusPiRo/ruspiro-mailbox", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]

[dependencies]
paste = "0.1.5"
ruspiro-register = { path = "../register", version = "0.3" }
ruspiro-singleton = { path = "../singleton", version = "0.3" }
ruspiro-cache = { path = "../cache", version = "0.3" }
ruspiro-console = { path = "../console", version = "0.3" }

[features]
default = ["ruspiro_pi3"]
ruspiro_pi3 = []
